package:
  name: travis-encrypt
  version: "1.0.0"

source:
  url: https://files.pythonhosted.org/packages/ff/48/62e01fbc7a4090cb1298b3027fa81080c110c28ed99a8f98d58fc87e5de6/travis-encrypt-1.0.0.tar.gz
  sha256: 9890807e0112ee8befcd0f4db320e4b58b7d5d8c7af2b3f28b51b8667f37a1c9
build:
  noarch: python
  number: 1
  entry_points:
    - travis-encrypt=travis.cli:cli
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - click >=6.7
    - cryptography >=1.9
    - pyyaml >=3.12
    - requests >=2.18.1

test:
  imports:
    - travis

  commands:
    - travis-encrypt --help

about:
  home: https://www.github.com/mandeep/Travis-Encrypt
  license: GPL-3.0
  summary: 'A command line application that encrypts passwords for use with Travis CI.'
  license_family: GPL3
  license_file: LICENSE

extra:
  recipe-maintainers:
   - mandeep
