travis:
  secure:
    BINSTAR_TOKEN: 01zfIxAofioyAqNKqEUylXsGg9JgWkmHG0QhpRKjyh0eLbcOIsnRbw3Qo0OpTADrhyf0wQ01EkjFbt+hco8dnU6EG8p0UqqdQdQRonucso8pDmaZ/m/rb02oE2ZIB2dcFqtlS0jydPXxbU/efz34Jg13gFHFZdguLqvjYz7eTOAn5no2n5bwf/dprhE9H2diVCDicl5TBYOHUuvwSya4cgxgKfuC4knbAFITb5by3xenYHrzeHB+BTsk1zMkM1Dils9RIGBS83IR1e/gcYue6Aa/6n6+u2cEb8MFxKRYcjYVvKMPGb6047yRebowYGIPSm9HYqOgYVCFK7PHUD7U4aFjMkpIM1vFPZmKTpnOykcYtL27zkhvd2d75qihSXB60p9tk2cQU+V3FO+2VGg60bP7nc+YdSFTC4jmDg09JvJ6y4pRA/R0ltee9C+lvjLjqTDOSSzgKaOzAB2a/kiK0q3E230cwUfAG84GdTX5L/N03PDK/9MQf/ps8KTMcRyUqYz2+ShH6t0tBtCNC5s0SQEnB5DlEEUpKL3kBBBxugiY8bsiRP7AbSl6S3bh7X6kV4JKiYspBYq1XWRkWrx1aiEWbnh5tl/uG318lzpbcs3f6FXKgZqRsdjQlPcInSekN0MOL+LBSWmHNtxttgrkwOeyUN12PzbiMs1E72VTxyg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
