travis:
  secure:
    BINSTAR_TOKEN: ruklxQyTUX2huZ4dlsQ6uxzAxNJfm8miAANvx9Kr9yY6PtXRlXKcJL9I943HPabwAXN8eAD2ipislbU0usXq6GJwrlWEZdVVVdjQA7k3t+1J3vwoVpESwgKPAgFbh73IxR7Az/V4ZXGhOz6Bvdsi3tFzgzFpoDrJAxP+7PFmQxGR/H1wy6XEOr7FEBt78JHvm1U/RbtNyW+sYtFRulmwNMKfy4GfJv8W0iuVBxNt/yLCGz0ihqBuRnIKKYIGxqBnWChGIzrCJTGUpGj/99sSDmiFN32NA0DRjFJfhXV3XWECotVJyxSyqnfahvXr5bZILCKl0baWRa+M7yconyDqT0URmEuL5BZgHcQokxnZAGZUEBLimPufYU/WE4Exl3P7wIuMES49TjwD3DxBCtdIQ42d5MVBWFmCF9gWlNrCsrTmtAnsi1NQWdN+6LZVjINYa86nW8VQtV10S5nbvIcbAzuWdxQs0zQhQdGJi8QBxUXciZI/ySnLge7vKb0MobIno2yzcK7ZnK85SKCyEFLKR0FDYxMNKPg/u3tOMV3pJkFGW2KQqp6BAzRLJXiTkDFzUiH9H90DlhaCiNt2JPTomwZQaeTacjnHCXnMkS0X3alnbodb8baaSrZLNHzn6VWln+B7Q8iilcu2vA2WxAzekTPMopbPpTPPiPiGkUiOz5w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
