travis:
  secure:
    BINSTAR_TOKEN: GHuo9VgN+erPzE040p83EXo6iAHlIuo9EIfMtjq1vxnY9/xbGbUOMDmxFlDzBwhYE61+CdSkyJZXYAcOmfR15CGu3nE2My6x9LcgvvGc6nvzDwVzAaI5j8JQgkaZpVhAHW1x5Hu51CKIwvDxvstF0zIS13+U8X4EnjLxUg5y5scsKdOKAbZT4IN4463XFaj9GtVPjaIKFxwxRDQtYGpIljvpfSV998MLAIolqUHO0fUYCUUFkv96beRsqbw4w0ULSHbIY+sCRY2We0CLRjnrnN7h127D2tSvOKloHJyO1pbjZSKErr08PIEj2+4oVqsmMiORGueTPMkkFm25fbUgdHBPrE2ResW5wgiDZUNIRkeriFoY3C2lH3TiTmCQx2gWg70hH1XrlI9mtWaARXFzRb2OtaJa3OadX/oRh4ZIlWBupEJW1Pap5nwnhrwBRnSio3PH3HOvgkG/cQU5x3x1qGdJVuuhauq9tvwG0uA/iteNnVrdKXZFXXM46HnGTE06V2TlXrL0+XTSOsBnh0PZPs7zjMhvlQQIOrA3wlym/OAe664CcTdDbT0LwPm3ppp9KyCcmw8sG6I5KI+K9mZIFJDhaOuTOJG3H5dGz4xqKpIquWJwz4wQeg+dVRkCMHr9u++j4jP4q3KTwJ8j/2pwT+LL6u3BqFUy7YcfrnTpAb0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
